version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./db:/app/db  # Corrected volume mapping
    environment:
      DATABASE_URL: sqlite:////app/db/db.sqlite3  # Corrected database URL
