version: '3'
services:
  database:
    image: 'sqlite'
    volumes:
      - ./data:/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=ROOT_USER
      - POSTGRES_PASSWORD=ROOT_USER
      - POSTGRES_DB=posts
